### ISSUE TITLE
@*.edu backend check

### ISSUE THREAD

**Issue by TannerS** [WebServiceIO/BookTradeSite#25]
implement regex for @*.edu emails

**Comment by dghermezi** [comment]
this regex should work

/^[a-zA-Z0-9]+@[a-zA-Z0-9]+.edu$/i

^ = beginning of string
[a-zA-Z0-9]+ = at least one of any letter or number
@ = literally @
[a-zA-Z0-9]+ = again at least one of any letter or number
. = "."
edu = "edu"
$ = end of string
/i = case insensitive
