### ISSUE TITLE
Responsive design implementation

### ISSUE THREAD

**Issue by c-nguyen** [WebServiceIO/BookTradeSite#3]
Index has been designed for large desktop screens. It needs to be changed so it supports smaller screens

**Comment by c-nguyen** [comment]
Index has new design with responsiveness. Everything complete except for banner

**Comment by TannerS** [comment]
update on this?

**Comment by c-nguyen** [comment]
I'm currently working on fixing the banner, so people can still see the banner on smaller devices.
Login and register pages are responsive, but I need to add a background.

**Comment by c-nguyen** [comment]
Index, login, and register pages are completely finished

**Comment by TannerS** [comment]
update?

**Comment by c-nguyen** [comment]
main account page, 3 account sub-pages, and create post are completely finished.

Pages currently not finished:
- results page
- individual book page
- view all current books user is selling page

**Comment by c-nguyen** [comment]
Finished individual book page

Pages currently not finished:
- results page
- view all current books user is selling page

**Comment by c-nguyen** [comment]
Everything is finished, except tables.
Tables are not responsive.
Will reopen if decide to fix it
