### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by TannerS** [WebServiceIO/BookTradeSite#9]
Make sure email and/or username validation is case INSENSITIVE, so fake@gmail.com is the same as Fake@gmail.com

**Comment by dghermezi** [comment]
is this just for logging in/registering?

**Comment by dghermezi** [comment]
fake@gmail.com is now the same as Fake@gmail.com 

we arent using username for logging in, but we can make that case insensitive if/when we implement that.
